### ISSUE TITLE
Newer library awailable: winsdk

### ISSUE THREAD

**Issue by roman-k-tech** [wolfmanstout/screen-ocr#14]
Hello,

Seems 'winrt' is outdated and not supported. There is community substitute and it has exactly same api:
Is that possible to move to newer one?

https://stackoverflow.com/questions/69610231/why-cant-pip-find-winrt
https://pypi.org/project/winsdk/#history

**Comment by wolfmanstout** [comment]
Waiting on this bug that I filed: https://github.com/pywinrt/python-winsdk/issues/20

**Comment by wolfmanstout** [comment]
winsdk was recently fixed and I have now switched over.
