### ISSUE TITLE
This module just OCRs the whole screen

### ISSUE THREAD

**Issue by ShobanChiddarth** [wolfmanstout/screen-ocr#16]
It just reads the whole screen and prints it as whole. How do I make it ocr only specific parts?

And where is the documentation?

**Comment by wolfmanstout** [comment]
I'm guessing you're referring to the behavior you get when running this module, i.e. "python -m screen_ocr". That's just a demo -- this package is intended as a library to be called by other Python code. It does support a bounding_box arg to restrict OCR to a portion of the screen:
https://github.com/wolfmanstout/screen-ocr/blob/ef2dcd10ff3df2d8742c7e1c3f839211de2f5fbb/screen_ocr/_screen_ocr.py#L220

The documentation is simply the code itself, which has docstrings. The file linked to above is the best starting point.

**Comment by ShobanChiddarth** [comment]
Ok
