### ISSUE TITLE
winrt doesn't work well with a single digit?

### ISSUE THREAD

**Issue by eight04** [wolfmanstout/screen-ocr#17]
![test](https://github.com/wolfmanstout/screen-ocr/assets/1324510/ff5bd37a-0ec6-4547-a4db-d41ede5b1a92)
While `pytesseract.image_to_string(im, config="--psm 6")` returns `6`.

**Comment by wolfmanstout** [comment]
Sounds entirely plausible especially with a dark background. It works best with flowing text. I don't have any control over this, so I'm closing.
