### ISSUE TITLE
"No module named 'winrt'" regardless of backend

### ISSUE THREAD

**Issue by tonydero** [wolfmanstout/screen-ocr#7]
Attempting to use this on Linux. I've tried installing it both in poetry 3.9.10 and 3.10.2 environments and my user system python (3.10.4) using either the tesseract or easyocr backends and whenever I try to run `python -m screen_ocr` to test if it is working, I get the `No module named 'winrt'` error. Apologies if this is a simple mistake on my part, but I'm at a loss right now.

**Comment by wolfmanstout** [comment]
Thank you for flagging this! I just pushed out a fix, along with a whole bunch of other improvements I've made since the last release. Let me know if you run into any more problems.
