### ISSUE TITLE
just select a rect rather than use radius

### ISSUE THREAD

**Issue by willwade** [wolfmanstout/screen-ocr#9]
Nice code!

I get why you are using radius as a selection technique (as demo'd in your tobii video) - but is there a simple way to just select say a specific rect on the page/. If I use radius I'm going to get stuff I don't need

(I basically am trying to capture the message bar area seen here: https://youtu.be/VPfV0_kevLk?t=69 - rather than all the other squares of words)

**Comment by wolfmanstout** [comment]
[`Reader.read_image()`](https://github.com/wolfmanstout/screen-ocr/blob/e5132770c1d40e85c6edbd24775ba1bf69b8a2db/screen_ocr/_screen_ocr.py#L222) will accept any arbitrary image, and you can set `screen_coordinates` and `search_radius` to None to search the entire image. You'll just need to take the screenshot yourself using `ImageGrab.grab()` and crop it, similar to [`Reader._screenshot_nearby()`](https://github.com/wolfmanstout/screen-ocr/blob/e5132770c1d40e85c6edbd24775ba1bf69b8a2db/screen_ocr/_screen_ocr.py#L267).

**Comment by willwade** [comment]
amazing. Thanks

**Comment by wolfmanstout** [comment]
FYI the API for this is now cleaner, see example: 
https://github.com/wolfmanstout/screen-ocr/blob/master/screen_ocr/__main__.py

Make sure to update to 0.4.0 (just pushed) to take advantage.
